application: Vane Guestbook
version: 1
deploy: true
pub: true
dart2js: true 

handlers:
- url: /posts/list
  match: exact 
  script: guestbook.dart
  handler: GetAllPosts
  
- url: /posts/add
  match: exact 
  script: guestbook.dart
  handler: SavePost
  
- url: /posts/delete
  match: exact 
  script: guestbook.dart
  handler: DeletePosts

# Static content  
- url: /
  match: postregex
  static_dir: web


